#include <stdio.h>
#include <string.h>

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

#include "esp_wifi.h"
#include "esp_event.h"
#include "esp_log.h"
#include "nvs_flash.h"
#include "esp_netif.h"

#include "esp_http_client.h"

#define WIFI_SSID      "YOUR_WIFI_SSID"
#define WIFI_PASSWORD  "YOUR_WIFI_PASSWORD"

#define SERVER_URL "http://192.168.77.16:3000/ask"

static const char *TAG = "PHASE_03_LLM";

/*
 * HTTP event handler
 *
 * This callback receives HTTP events generated by ESP-IDF.
 * We use HTTP_EVENT_ON_DATA to receive the backend response.
 */
esp_err_t http_event_handler(
    esp_http_client_event_t *evt)
{
    switch (evt->event_id)
    {
        case HTTP_EVENT_ON_DATA:

            ESP_LOGI(TAG, "LLM Response:");

            printf("%.*s\n",
                   evt->data_len,
                   (char *)evt->data);

            break;

        default:
            break;
    }

    return ESP_OK;
}

/*
 * Wi-Fi event handler
 */
static void wifi_event_handler(
    void *arg,
    esp_event_base_t event_base,
    int32_t event_id,
    void *event_data)
{
    if (event_base == WIFI_EVENT &&
        event_id == WIFI_EVENT_STA_START)
    {
        ESP_LOGI(TAG, "Connecting to Wi-Fi...");

        esp_wifi_connect();
    }

    else if (event_base == IP_EVENT &&
             event_id == IP_EVENT_STA_GOT_IP)
    {
        ip_event_got_ip_t *event =
            (ip_event_got_ip_t *) event_data;

        ESP_LOGI(
            TAG,
            "Got IP: " IPSTR,
            IP2STR(&event->ip_info.ip));
    }

    else if (event_base == WIFI_EVENT &&
             event_id == WIFI_EVENT_STA_DISCONNECTED)
    {
        ESP_LOGW(TAG, "Wi-Fi disconnected");

        esp_wifi_connect();
    }
}

/*
 * Initialize Wi-Fi station mode
 */
void wifi_init_sta(void)
{
    esp_netif_create_default_wifi_sta();

    wifi_init_config_t cfg =
        WIFI_INIT_CONFIG_DEFAULT();

    ESP_ERROR_CHECK(
        esp_wifi_init(&cfg));

    ESP_ERROR_CHECK(
        esp_event_handler_instance_register(
            WIFI_EVENT,
            ESP_EVENT_ANY_ID,
            &wifi_event_handler,
            NULL,
            NULL));

    ESP_ERROR_CHECK(
        esp_event_handler_instance_register(
            IP_EVENT,
            IP_EVENT_STA_GOT_IP,
            &wifi_event_handler,
            NULL,
            NULL));

    wifi_config_t wifi_config = {
        .sta = {
            .ssid = WIFI_SSID,
            .password = WIFI_PASSWORD,
        },
    };

    ESP_ERROR_CHECK(
        esp_wifi_set_mode(WIFI_MODE_STA));

    ESP_ERROR_CHECK(
        esp_wifi_set_config(
            WIFI_IF_STA,
            &wifi_config));

    ESP_ERROR_CHECK(
        esp_wifi_start());
}

/*
 * Send HTTP POST request to backend API
 */
void send_http_post(void)
{
    esp_http_client_config_t config = {
        .url = SERVER_URL,
        .timeout_ms = 30000,
        .event_handler = http_event_handler,
    };

    esp_http_client_handle_t client =
        esp_http_client_init(&config);

    /*
     * JSON payload sent to backend API
     */
    const char *json_data =
        "{\"message\":\"What is M5Stack?\"}";

    esp_http_client_set_method(
        client,
        HTTP_METHOD_POST);

    esp_http_client_set_header(
        client,
        "Content-Type",
        "application/json");

    esp_http_client_set_post_field(
        client,
        json_data,
        strlen(json_data));

    ESP_LOGI(TAG, "Sending HTTP POST...");

    esp_err_t err =
        esp_http_client_perform(client);

    if (err == ESP_OK)
    {
        int status =
            esp_http_client_get_status_code(client);

        ESP_LOGI(
            TAG,
            "HTTP Status = %d",
            status);

        ESP_LOGI(
            TAG,
            "LLM request completed successfully");
    }
    else
    {
        ESP_LOGE(
            TAG,
            "HTTP POST failed: %s",
            esp_err_to_name(err));
    }

    esp_http_client_cleanup(client);
}

/*
 * Main firmware entry point
 */
void app_main(void)
{
    esp_err_t ret;

    /*
     * Initialize NVS
     */
    ret = nvs_flash_init();

    if (ret == ESP_ERR_NVS_NO_FREE_PAGES ||
        ret == ESP_ERR_NVS_NEW_VERSION_FOUND)
    {
        ESP_ERROR_CHECK(
            nvs_flash_erase());

        ret = nvs_flash_init();
    }

    ESP_ERROR_CHECK(ret);

    /*
     * Initialize TCP/IP stack
     */
    ESP_ERROR_CHECK(
        esp_netif_init());

    /*
     * Create default event loop
     */
    ESP_ERROR_CHECK(
        esp_event_loop_create_default());

    /*
     * Start Wi-Fi
     */
    wifi_init_sta();

    /*
     * Wait for network stabilization
     */
    vTaskDelay(pdMS_TO_TICKS(10000));

    /*
     * Send request to backend LLM API
     */
    send_http_post();

    /*
     * Main loop
     */
    while (1)
    {
        vTaskDelay(pdMS_TO_TICKS(10000));
    }
}